apiVersion: v1
kind: Secret
metadata:
  name: sre-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ .Values.external.rabbitmqUrl | quote }}
  REDIS_PASSWORD: {{ .Values.external.redisPassword | quote }}
  MYSQL_DSN: {{ .Values.external.mysqlDsn | quote }}
  MYSQL_PASSWORD: {{ .Values.external.mysqlPassword | quote }}
  DINGTALK_WEBHOOK: {{ .Values.agent.dingTalkWebhook | quote }}
