apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-app
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: crash-app } }
  template:
    metadata: { labels: { app: crash-app } }
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c", "echo start; sleep 5; exit 1"]
