apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-image-app
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: bad-image-app } }
  template:
    metadata: { labels: { app: bad-image-app } }
    spec:
      containers:
        - name: app
          image: registry.example.com/not-exist/app:v0.0.1
